### ISSUE TITLE
Compile the driver on an raspberry pi :)

### ISSUE THREAD

**Issue by gamecompiler** [bengtmartensson/DevSlashLirc#7]
apt-get install maven oracle-java7-jdk
exchange the makefile i attached in /src/main/c++
Id had to change/add some includes

[Makefile.zip](https://github.com/bengtmartensson/DevSlashLirc/files/1344670/Makefile.zip)

The only thing id got stuck is to install the built. Could you please help me with that?
It would be quite awesome to use the driver on a raspberry pi because the current liblirc isnt ported currently for the Rpi.

**Comment by bengtmartensson** [comment]
I added a section to the README.md. Does it solve your problem?

It is "normal" that include paths needs to be tweaked, as long as #2 is not implemented. #2 should be the definite solution.

**Comment by bengtmartensson** [comment]
OK to close?

**Comment by gamecompiler** [comment]
Yup, I'll do that tomorrow when I'm at home. Am 01.10.2017 08:56 schrieb Bengt Martensson <notifications@github.com>:OK to close?
